#+title: Monte Carlo Project
#+author: R

* Stochastic Differential Equation (SDE) Solver

This project implements a high performance SDE solver. It employs number of approaches towards solving a defined Stochastic Differential Equation modelling a stock price, and later Monte Carlo methods for estimating the price of a Bermudan shout option on the stock. Numpy and Numbas are used for optimal memory and runtime efficiency within Python.

$$d S_t = S_t \mu dt + S_t \sigma [1 + 0.9 \sin (2 \pi t)] d W_t$$

A seasonal volatility model is solved in the [[file:Report.pdf][full report]]. The [[file:Main.py][main file]] and [[file:testing.py][unit testing]] files are also available.

* C++ Integration

** Monte Carlo Sampling Library

This project features a Main Monte Carlo engine written entirely in C++, which connects to Python using [[https://github.com/pybind/pybind11][pybind11]]. The high speed library includes an inverse quantile transform leveraging Padé approximation based on Abramowitz and Stegun. Documentation is included [[file:docs/html/index.html][for library functions]]. All functions export to vectorised numpy arrays, which work extremely well with pandas and numpy functions in general. This ensures seamless integration into existing toolsets.

** Unit Testing

This project uses [[https://github.com/google/googletest][Google Test]] to validate internal function accuracy, ensuring that the logic remains reliable under changes. Tests can be accessed by using the typical CTest commands (`cmake --build build --target test`).



* Features

** Euler-Maruyama (EM) scheme
1. Baseline model for comparisons,
2. Numpy accelerated version,
3. Numbas accelerated version,

** Function Benchmarking
1. Performance timing for EM models,
2. Time complexity across sampling and chains shown on clear 3d pyplot,

** Accuracy Analysis
1. Exact solution calculated for efficiency estimates,
2. Errors quantified and visualised,

** Runge-Kutta (RK) scheme
1. Highly efficient RK scheme implemented in numpy,
2. Strong and weak convergence for path-dependent options,

** Exotic option pricing
1. Use of numpy accelerated Monte Carlo sampling of RK scheme to price Bermudan shout option,
2. *Antithetic sampling* for higher efficiency,
3. Visualisation of paths and convergence,

** Unit Testing and Input Validation
1. Use of pytest to ensure edge cases considered,
2. Input validation function for function safety.

* Installation

If you have git and pip,

#+begin_src shell
  # download project
  git clone https://github.com/ghost9639/MATH5350-Assessment-2
  cd MATH5350-Assessment-2

  # install any required dependencies
  pip install numpy numba matplotlib pytest

  # alternatively, if you have nix
  nix-shell
#+end_src

** Building Local Library

Building the local library is easy and requires relatively few build tools, depending on a C++17 installation, CMake (any version above 3.5), Git, and Ninja. On MacOS / Linux:

#+begin_src shell
  git clone https://github.com/ghost9639/Monte-Carlo-Engine
  cd Monte-Carlo-Engine

  rm -rf build
  mkdir build

  cmake -S . -B build -G Ninja
  cmake --build build

  export PYTHONPATH=$PYTHONPATH:$(pwd)/build
  python <YOUR_PYTHON_FILE>
#+end_src

On Windows:

#+begin_src shell
  git clone https://github.com/ghost9639/Monte-Carlo-Engine
  cd Monte-Carlo-Engine

  cmake -S . -B build -G Ninja
  cmake --build build

  # One of:
  set PYTHONPATH=%PYTHONPATH%;%cd%\build # if using cmd
  $env:PYTHONPATH = "$env:PYTHONPATH;$(Get-Location)\build" # if using powershell

  python <YOUR_PYTHON_FILE>
#+end_src


* Project Insights

1. Numpy acceleration and Numba JIT compilation for high efficiency compared to base Python,
2. Euler-Maruyama is easily debugged but lacks weak convergence for path independent options,
3. Runge-Kutta scheme has higher computational cost but weak convergence,
4. Antithetic sampling for faster convergence,


* Potential Improvements

1. GPU acceleration,
2. Further MC methods,
3. Support for general and multi-dimensional SDEs,
4. Calibration for real data.
